# Generated by Django 3.1.6 on 2021-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meme', '0002_auto_20210209_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
